### ISSUE TITLE
 at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

### ISSUE THREAD

**Issue by fanne** [webbought/imoocDownloader#16]
##### 下载的时候报错
错误日志
```bash
[2016-12-12 18:11:08.977] [ERROR] error - { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
[2016-12-12 18:13:38.267] [ERROR] error - { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
````

下载时候输出
```bash
[root@localhost imoocDownloader]# node index.js --download 763
>>>
正在下载课程 :  TypeScript入门
+ -- 第1章初识TypeScript
+ --- 1-1TypeScript-TypeScript介绍(01:41)
+ --- 1-2TypeScript-课程内容介绍(02:21)
+ -- 第2章TypeScript的优势
+ --- 2-1TypeScript-TypeScript的优势(02:37)
+ -- 第3章搭建TypeScript开发环境
+ --- 3-1TypeScript-在线compiler(02:00)
+ --- 3-2TypeScript-本地compiler(07:23)
+ -- 第4章字符串新特性
+ --- 4-1TypeScript-字符串新特性(08:17)
+ -- 第5章参数新特性
+ --- 5-1TypeScript-参数类型(06:06)
+ --- 5-2TypeScript-参数默认值(03:00)
+ --- 5-3TypeScript-可选参数(02:32)
+ -- 第6章函数新特性
+ --- 6-1TypeScript-RestandSpread操作符(05:02)
+ --- 6-2TypeScript-generator函数(07:30)
+ --- 6-3TypeScript-析构表达式(09:48)
+ -- 第7章表达式与循环
+ --- 7-1TypeScript-箭头表达式(07:39)
+ --- 7-2TypeScript-forof循环(07:16)
+ -- 第8章面向对象特性
+ --- 8-1TypeScript-类(15:07)
+ --- 8-2TypeScript-泛型(02:06)
+ --- 8-3TypeScript-接口(05:18)
+ --- 8-4TypeScript-模块(04:53)
+ --- 8-5TypeScript-注解(02:42)
+ --- 8-6TypeScript-类型定义文件(04:41)
+ -- 第9章课程总结
+ --- 9-1TypeScript-总结(00:52)
<<<
[root@localhost imoocDownloader]# 
```

没有正常下载，只打印出列表后就没有后续下载动作了。

**Comment by t2krew** [comment]
@fanne 看报错应该是网络连接失败了。

**Comment by t2krew** [comment]
@fanne [http://stackoverflow.com/questions/17245881/node-js-econnreset](http://stackoverflow.com/questions/17245881/node-js-econnreset)
