### ISSUE TITLE
亲测失效

### ISSUE THREAD

**Issue by ooing** [webbought/imoocDownloader#20]
比如 下载 http://www.imooc.com/learn/790  这个 ，只能下载 第一个视频

**Comment by t2krew** [comment]
@ooing 你去看下log有没有异常记录。有的话贴下日志，跑的机器不一样，你这样 写个 亲测失败 我也无法debug，目前其他人都能正常跑。

**Comment by ooing** [comment]
@t2krew 抱歉,  我没看到 这个项目是有日志功能

2017-01-12 10:03:39.788] [ERROR] error - [Error: 缺少目标url]
Error: 缺少目标url
    at module.exports (H:\muke\nodejs\imoocDownloader\lib\downLoader.js:17:21)
    at H:\muke\nodejs\imoocDownloader\imooc.js:196:7
    at H:\muke\nodejs\imoocDownloader\imooc.js:231:23
    at IncomingMessage.<anonymous> (H:\muke\nodejs\imoocDownloader\lib\urllib.js:77:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by joriscai** [comment]
应该是慕课网对视频更换策略了，现在在旧版本的chrome浏览器中，无法用h5模式观看视频。用了新的chrome，可以用h5模式，并抓包看到视频也是分段传输了 @t2krew

**Comment by t2krew** [comment]
@joriscai 嗯，刚去看了下确实是。  @ooing

**Comment by joriscai** [comment]
还有什么方法来破解下载吗？前端视频方面还没有研究，请大大指教一下 @t2krew

**Comment by t2krew** [comment]
@joriscai 我也是新手来的，相互学习哈。最近比较忙，放假再研究下
