### ISSUE TITLE
不能用啊，下载回来只有文件夹和txt文件，视频文件下载不了

### ISSUE THREAD

**Issue by VAEAZE** [webbought/imoocDownloader#24]
不能用啊，下载回来只有文件夹和txt文件，视频文件下载不了

**Comment by VAEAZE** [comment]
[2017-05-26 15:46:54.774] [ERROR] error - Error: 缺少目标url
    at module.exports (D:\software\imooc-master\imoocDownloader-master\lib\downLoader.js:17:21)
    at D:\software\imooc-master\imoocDownloader-master\imooc.js:195:7
    at D:\software\imooc-master\imoocDownloader-master\imooc.js:230:23
    at IncomingMessage.<anonymous> (D:\software\imooc-master\imoocDownloader-master\lib\urllib.js:77:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by VAEAZE** [comment]
测试了有些链接可以下，有些不可用；如713不可用

**Comment by kean12** [comment]
7** 开头的就不能用了。
